title: Bloomington Blades Youth Hockey Association
author: BBYHA
email: kalanicraig@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Play USA Hockey sanctioned hockey with the Bloomington Blades Youth Hockey Association in Bloomington, Indiana

twitter_username: kalanicraig
github_username:  kalanicraig

sass:
    style: compressed